# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69621d388b72a37a2e460d5e41dba92c6fab6d2b8fbd9ce935e860c2e8186f7ecebdb83438e03105e3747cb02675d69a576bb7390c7101f7c2cca9b0b8c9b05b

test:
  secret_key_base: d4969fdadf329bb700eb112ff15386617e1e935521d660844a6e48282925dcb60d326b56822ef72e4d334d2fa0784b118c320c67a565deb6d33bbde7b9d1e415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
